name: test

on: push

env:
  GRADLE_OPTS: '-Dorg.gradle.daemon=false'

jobs:
  mytest:
    strategy:
      fail-fast: false # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstrategyfail-fast
      matrix:
        agpVersion:
          - '3.5.0'
          - '3.5.4'
          - '3.6.0'
          - '3.6.4'
          - '4.0.0'
          - '4.0.2'
          - '4.1.0'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - uses: android-actions/setup-android@v2
      - run: ./mylib/gradlew --project-dir=./mylib/ :mylib:publishReleasePublicationToMavenLocal
      - run: echo 'myproj.agpVersion=${{ matrix.agpVersion }}' >> ./appproj/defs.properties
      - run: ./appproj/gradlew --project-dir=./appproj/ :app:assemble
